// Reqres API response:
// {
//   "id": 1,
//   "email": "george.bluth@reqres.in",
//   "first_name": "George",
//   "last_name": "Bluth",
//   "avatar": "https://reqres.in/img/faces/1-image.jpg"
// }

class UserModel {
  final int id;
  final String email;
  final String firstName;
  final String lastName;
  final String avatar;

  // "Movie Taste" — maps to `job` field when creating user
  final String movieTaste;

  // How many movies this user has saved (computed locally, not from API)
  final int savedMoviesCount;

  const UserModel({
    required this.id,
    required this.email,
    required this.firstName,
    required this.lastName,
    required this.avatar,
    this.movieTaste = '',
    this.savedMoviesCount = 0,
  });

  String get fullName => '$firstName $lastName'.trim();

  // From Reqres API JSON
  factory UserModel.fromJson(Map<String, dynamic> json) => UserModel(
        id: json['id'] as int,
        email: json['email'] as String? ?? '',
        firstName: json['first_name'] as String? ?? '',
        lastName: json['last_name'] as String? ?? '',
        avatar: json['avatar'] as String? ?? '',
        movieTaste: json['job'] as String? ?? '',
      );

  // From local Drift DB row (UserData)
  factory UserModel.fromDb(UserData db, {int savedMoviesCount = 0}) => UserModel(
        id: db.serverId ?? db.id, // prefer server ID
        email: db.email,
        firstName: db.firstName,
        lastName: db.lastName,
        avatar: db.avatarUrl,
        movieTaste: db.movieTaste,
        savedMoviesCount: savedMoviesCount,
      );

  UserModel copyWith({int? savedMoviesCount}) => UserModel(
        id: id,
        email: email,
        firstName: firstName,
        lastName: lastName,
        avatar: avatar,
        movieTaste: movieTaste,
        savedMoviesCount: savedMoviesCount ?? this.savedMoviesCount,
      );
}

// Drift generated class — just a type alias hint for fromDb()
// (actual UserData class is generated by build_runner)
typedef UserData = dynamic; // remove this line after build_runner runs
